"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { Bar, BarChart, CartesianGrid, Cell, Line, LineChart, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";

const colors = ["#A7D8F0", "#FFF3C4", "#D6ECF7", "#24485C", "#8EBBD3", "#C9DCE5"];
type Data = { achievements: { years: { year: string; count: number }[]; byType: { name: string; value: number }[] }; todos: { weeks: { label: string; created: number; completed: number; overdue: number }[]; status: { name: string; value: number }[]; recentRate: number }; footprints: { countries: number; provinces: number }; inspirations: { categories: { name: string; value: number }[]; subCategories: { name: string; value: number }[]; months: { month: string; count: number }[] } };
const empty: Data = { achievements: { years: [], byType: [] }, todos: { weeks: [], status: [], recentRate: 0 }, footprints: { countries: 0, provinces: 0 }, inspirations: { categories: [], subCategories: [], months: [] } };
function Card({ title, children, className = "" }: { title: string; children: React.ReactNode; className?: string }) { return <section className={`analytics-card ${className}`}><div className="analytics-card-heading"><h2>{title}</h2><span>可交互查看详情</span></div>{children}</section> }
function Empty() { return <div className="analytics-empty">✦<p>还没有可展示的数据</p></div> }
function Donut({ data }: { data: { name: string; value: number }[] }) { return data.some((item) => item.value) ? <ResponsiveContainer width="100%" height={230}><PieChart><Pie data={data} dataKey="value" nameKey="name" innerRadius={62} outerRadius={88} paddingAngle={3}>{data.map((item, i) => <Cell key={item.name} fill={colors[i % colors.length]} />)}</Pie><Tooltip formatter={(value, name) => [`${value} 条`, name]} /></PieChart></ResponsiveContainer> : <Empty /> }
export function AnalyticsDashboard() { const [range, setRange] = useState("all"); const [data, setData] = useState<Data>(empty); useEffect(() => { fetch(`/api/analytics?range=${range}`).then((res) => res.json()).then(setData); }, [range]); const exportCsv = () => { const rows = [["年份","成就数量"], ...data.achievements.years.map((x) => [x.year, x.count])]; const blob = new Blob([rows.map((r) => r.join(",")).join("\n")], { type: "text/csv;charset=utf-8" }); const url = URL.createObjectURL(blob); const a = document.createElement("a"); a.href = url; a.download = "analytics.csv"; a.click(); URL.revokeObjectURL(url); };
  return <div className="analytics-dashboard"><div className="analytics-toolbar"><div className="range-tabs">{[["month","本月"],["year","本年"],["all","全部"]].map(([value, label]) => <button key={value} className={range === value ? "active" : ""} onClick={() => setRange(value)}>{label}</button>)}</div><button className="ghost-button" onClick={exportCsv}>导出 CSV</button></div><div className="analytics-grid"><Card title="成就年份分布"><div className="analytics-chart"><ResponsiveContainer width="100%" height={250}><BarChart data={data.achievements.years} onClick={(event) => { const year = event?.activeLabel; if (year) window.location.href = `/achievements?year=${year}`; }}><CartesianGrid strokeDasharray="3 3" stroke="#D6ECF7" /><XAxis dataKey="year" /><YAxis allowDecimals={false} /><Tooltip formatter={(v) => [`${v} 条`, "成就"]} /><Bar dataKey="count" fill="#A7D8F0" radius={[7, 7, 0, 0]} /></BarChart></ResponsiveContainer></div></Card><Card title="成就类型占比"><div className="analytics-chart"><Donut data={data.achievements.byType} /></div><div className="analytics-legend">{data.achievements.byType.map((item, i) => <Link href={`/achievements?type=${encodeURIComponent(item.name)}`} key={item.name}><i style={{ background: colors[i % colors.length] }} />{item.name} {item.value}</Link>)}</div></Card><Card title="待办完成率"><div className="analytics-rate"><strong>{Math.round(data.todos.recentRate * 100)}%</strong><span>最近 30 天完成率</span></div><ResponsiveContainer width="100%" height={190}><LineChart data={data.todos.weeks}><CartesianGrid strokeDasharray="3 3" stroke="#D6ECF7" /><XAxis dataKey="label" /><YAxis allowDecimals={false} /><Tooltip /><Line type="monotone" dataKey="created" name="新增" stroke="#A7D8F0" strokeWidth={3} /><Line type="monotone" dataKey="completed" name="完成" stroke="#24485C" strokeWidth={3} /><Line type="monotone" dataKey="overdue" name="逾期" stroke="#D8C98A" strokeWidth={3} /></LineChart></ResponsiveContainer></Card><Card title="待办状态"><Donut data={data.todos.status} /></Card><Card title="足迹进度" className="analytics-footprints"><Progress label="已去过国家" value={data.footprints.countries} total={195} /><Progress label="已去过中国省级行政区" value={data.footprints.provinces} total={34} /><Link href="/footprints" className="ghost-button">查看足迹地图</Link></Card><Card title="灵感分类占比"><Donut data={data.inspirations.categories} /><div className="analytics-legend">{data.inspirations.categories.map((item, i) => <span key={item.name}><i style={{ background: colors[i % colors.length] }} />{item.name} {item.value}</span>)}</div></Card><Card title="灵感二级标签" className="analytics-wide"><div className="analytics-bars">{data.inspirations.subCategories.map((item) => <div key={item.name}><span>{item.name}</span><b style={{ width: `${Math.max(item.value / Math.max(...data.inspirations.subCategories.map((x) => x.value), 1) * 100, 4)}%` }}>{item.value}</b></div>)}</div></Card></div></div> }
function Progress({ label, value, total }: { label: string; value: number; total: number }) { return <div className="analytics-progress"><div><span>{label}</span><strong>{value} / {total}</strong></div><div className="progress-track"><i style={{ width: `${Math.min(value / total * 100, 100)}%` }} /></div></div> }
