"use client";
import Link from "next/link";
import { usePathname, useRouter } from "next/navigation";
import { LogOut, Moon, Sparkles, Sun } from "lucide-react";
import { useEffect, useState, type ReactNode } from "react";
import { WebMcpTools } from "@/components/webmcp-tools";
import { GlobalSearch } from "@/components/global-search";
import { NotificationBell } from "@/components/notification-bell";

const navigation = [{href:"/",label:"主页"},{href:"/achievements",label:"成就"},{href:"/todos",label:"待办"},{href:"/footprints",label:"足迹"},{href:"/inspiration",label:"审美灵感"},{href:"/yearly/2026",label:"年度总结"},{href:"/dashboard/analytics",label:"数据面板"},{href:"/admin",label:"管理后台"}];
function ThemeToggle(){const[dark,setDark]=useState(false);useEffect(()=>{const saved=localStorage.getItem("theme");const next=saved?saved==="dark":matchMedia("(prefers-color-scheme: dark)").matches;document.documentElement.dataset.theme=next?"dark":"light";const frame=requestAnimationFrame(()=>setDark(next));return()=>cancelAnimationFrame(frame)},[]);function toggle(){const next=!dark;setDark(next);localStorage.setItem("theme",next?"dark":"light");document.documentElement.dataset.theme=next?"dark":"light"}return <button className="shell-icon-button" onClick={toggle} aria-label={dark?"切换浅色模式":"切换暗色模式"}>{dark?<Sun size={18}/>:<Moon size={18}/>}</button>}
export function DashboardShell({title,subtitle,action,children}:{title?:string;subtitle?:string;action?:ReactNode;children:ReactNode}){const pathname=usePathname();const router=useRouter();async function logout(){await fetch("/api/auth/logout",{method:"POST"});router.replace("/login");router.refresh()}return <div className="app-shell top-shell"><WebMcpTools/><header className="site-header"><Link href="/" className="brand top-brand"><span className="brand-mark"><Sparkles size={20}/></span><span><strong>拾光簿</strong><small>PERSONAL LOG</small></span></Link><nav className="top-navigation" aria-label="主导航">{navigation.map(item=><Link key={item.href} href={item.href} className={pathname===item.href?"active":""}>{item.label}</Link>)}</nav><div className="header-actions"><GlobalSearch/><ThemeToggle/><button className="shell-logout" onClick={logout}><LogOut size={17}/><span>退出登录</span></button></div></header><main className="main-panel top-main">{title&&<header className="topbar"><div><p className="eyebrow">MY PERSONAL ARCHIVE</p><h1>{title}</h1>{subtitle&&<p>{subtitle}</p>}</div>{action&&<div className="top-actions">{action}</div>}</header>}{children}<footer className="site-footer"><Link href="/" className="footer-brand"><span className="footer-bow">୨୧</span><span><strong>拾光簿</strong><small>PERSONAL LOG</small></span></Link><nav aria-label="页脚导航">{navigation.slice(0,5).map(item=><Link key={item.href} href={item.href}>{item.label}</Link>)}</nav><span className="footer-note">记录生活，也记录正在发生的事 · © 2026</span></footer></main></div>}
