"use client";

import { Minus, Plus, RotateCcw, Search, Trash2, X } from "lucide-react";
import { useEffect, useMemo, useRef, useState } from "react";
import { ComposableMap, Geographies, Geography, ZoomableGroup } from "react-simple-maps";
import world from "../public/geo/countries-50m.json";
import chinaData from "../public/geo/china-provinces.json";

const commonCountryZh: Record<string, string> = { "499": "黑山", "070": "波斯尼亚和黑塞哥维那", "688": "塞尔维亚", "008": "阿尔巴尼亚", "191": "克罗地亚", "705": "斯洛文尼亚", "807": "北马其顿", "642": "罗马尼亚", "100": "保加利亚", "348": "匈牙利", "203": "捷克", "703": "斯洛伐克", "208": "丹麦", "352": "冰岛", "504": "摩洛哥", " Tunisia": "突尼斯" };

export type FootprintItem = { id: number; scope: string; countryCode: string | null; countryNameZh: string | null; countryNameEn: string | null; provinceCode: string | null; provinceNameZh: string | null; provinceNameEn: string | null; visited: boolean; isPublic?: boolean; visitedAt?: string | null };
type Choice = { code: string; zh: string; en: string; scope: "country" | "china-province" };

const chinaFeatures = chinaData.features.filter((feature) => /^\d{6}$/.test(String(feature.properties?.adcode)));
const chinaPath = (feature: (typeof chinaFeatures)[number]) => {
  const rings = (feature.geometry.type === "Polygon" ? feature.geometry.coordinates : feature.geometry.coordinates.flat()) as [number, number][][];
  return rings.map((ring) => ring.map(([longitude, latitude], index) => `${index ? "L" : "M"}${(longitude - 70) * 9.8},${(55 - latitude) * 8.7}`).join("") + "Z").join("");
};
const countryNames: Record<string, string> = { "156": "中国", "392": "日本", "840": "美国", "826": "英国", "250": "法国", "276": "德国", "380": "意大利", "724": "西班牙", "036": "澳大利亚", "124": "加拿大", "410": "韩国", "764": "泰国", "702": "新加坡", "458": "马来西亚", "360": "印度尼西亚", "356": "印度", "643": "俄罗斯", "076": "巴西", "484": "墨西哥", "710": "南非", "818": "埃及", "792": "土耳其", "784": "阿联酋", "608": "菲律宾", "554": "新西兰", "528": "荷兰", "056": "比利时", "756": "瑞士", "752": "瑞典", "578": "挪威", "246": "芬兰", "620": "葡萄牙", "300": "希腊", "616": "波兰", "040": "奥地利", "372": "爱尔兰", "344": "香港", "446": "澳门", "158": "台湾", "144": "斯里兰卡", "462": "马尔代夫" };
const provinceEnglish: Record<string, string> = { "北京市": "Beijing", "天津市": "Tianjin", "上海市": "Shanghai", "重庆市": "Chongqing", "河北省": "Hebei", "山西省": "Shanxi", "辽宁省": "Liaoning", "吉林省": "Jilin", "黑龙江省": "Heilongjiang", "江苏省": "Jiangsu", "浙江省": "Zhejiang", "安徽省": "Anhui", "福建省": "Fujian", "江西省": "Jiangxi", "山东省": "Shandong", "河南省": "Henan", "湖北省": "Hubei", "湖南省": "Hunan", "广东省": "Guangdong", "海南省": "Hainan", "四川省": "Sichuan", "贵州省": "Guizhou", "云南省": "Yunnan", "陕西省": "Shaanxi", "甘肃省": "Gansu", "青海省": "Qinghai", "台湾省": "Taiwan", "内蒙古自治区": "Inner Mongolia", "广西壮族自治区": "Guangxi", "西藏自治区": "Tibet", "宁夏回族自治区": "Ningxia", "新疆维吾尔自治区": "Xinjiang", "香港特别行政区": "Hong Kong", "澳门特别行政区": "Macao" };
const aliases: Record<string, Choice> = { "日本": { code: "392", zh: "日本", en: "Japan", scope: "country" }, japan: { code: "392", zh: "日本", en: "Japan", scope: "country" }, tokyo: { code: "392", zh: "日本", en: "Japan", scope: "country" }, "上海": { code: "310000", zh: "上海市", en: "Shanghai", scope: "china-province" }, shanghai: { code: "310000", zh: "上海市", en: "Shanghai", scope: "china-province" }, "台湾": { code: "710000", zh: "台湾省", en: "Taiwan", scope: "china-province" }, "台湾省": { code: "710000", zh: "台湾省", en: "Taiwan", scope: "china-province" }, taiwan: { code: "710000", zh: "台湾省", en: "Taiwan", scope: "china-province" }, california: { code: "840", zh: "美国", en: "United States of America", scope: "country" }, "美国": { code: "840", zh: "美国", en: "United States of America", scope: "country" }, china: { code: "156", zh: "中国", en: "China", scope: "country" }, "中国": { code: "156", zh: "中国", en: "China", scope: "country" } };
const clean = (value: string) => value.trim().toLowerCase().replace(/[\s,，.]/g, "");
const keyOf = (choice: Choice) => `${choice.scope}:${choice.code}`;
const provinceChoice = (feature: (typeof chinaFeatures)[number]): Choice => { const zh = String(feature.properties?.name); return { scope: "china-province", code: String(feature.properties?.adcode), zh, en: provinceEnglish[zh] || zh }; };
const resolveChoice = (query: string): Choice | null => { const normalized = clean(query); if (aliases[normalized]) return aliases[normalized]; const feature = chinaFeatures.find((item) => { const zh = String(item.properties?.name); const short = zh.replace(/(?:壮族|回族|维吾尔族)?自治区|省|特别行政区/g, ""); const en = provinceEnglish[zh] || ""; return [zh, short, en].some((value) => clean(value) === normalized); }); if (feature) return provinceChoice(feature); const country = world.objects?.countries?.geometries?.find((item: any) => clean(String(item.properties?.name || "")) === normalized); if (country) { const code = String(country.id); return { scope: "country", code: ["158", "344", "446"].includes(code) ? "156" : code, zh: countryNames[code] || String(country.properties?.name || code), en: String(country.properties?.name || code) }; } return null; };
const fromItem = (item: FootprintItem): Choice | null => item.scope === "country" && item.countryCode ? { scope: "country", code: item.countryCode, zh: item.countryNameZh || item.countryNameEn || item.countryCode, en: item.countryNameEn || item.countryNameZh || item.countryCode } : item.scope === "china-province" && item.provinceCode ? { scope: "china-province", code: item.provinceCode, zh: item.provinceNameZh || item.provinceCode, en: item.provinceNameEn || item.provinceNameZh || item.provinceCode } : null;

function MapButtons({ onZoom, onReset }: { onZoom: (amount: number) => void; onReset: () => void }) { return <div className="map-controls"><button type="button" onClick={() => onZoom(.5)} aria-label="放大"><Plus size={17} /></button><button type="button" onClick={() => onZoom(-.5)} aria-label="缩小"><Minus size={16} /></button><button type="button" onClick={onReset} aria-label="重置地图"><RotateCcw size={16} /></button></div>; }

function ChinaMap({ compact = false }: { selected: Map<string, Choice>; onToggle?: (choice: Choice) => void; compact?: boolean }) { return <div className={`footprint-map china-map ${compact ? "compact" : ""}`} style={{ background: "#e9f6fb" }}><img className="official-china-map" src="/geo/official/4o28b0625501ad13015501ad2bfc0135.jpg" alt="中华人民共和国地图（含南海诸岛附图）" /></div>; }

function WorldMap({ selected, onToggle, compact = false }: { selected: Map<string, Choice>; onToggle?: (choice: Choice) => void; compact?: boolean }) { const [position, setPosition] = useState<[number, number]>([0, 0]); const [zoom, setZoom] = useState(1); return <div className={`footprint-map ${compact ? "compact" : ""}`}>{!compact && <MapButtons onZoom={(amount) => setZoom((value) => Math.max(1, Math.min(4, value + amount)))} onReset={() => { setPosition([0, 0]); setZoom(1); }} />}<ComposableMap width={800} height={430} className="footprint-map-svg"><ZoomableGroup center={position} zoom={compact ? 1 : zoom} minZoom={1} maxZoom={4} onMoveEnd={({ coordinates, zoom: nextZoom }) => { if (!compact) { setPosition(coordinates as [number, number]); setZoom(nextZoom); } }} filterZoomEvent={() => !compact}><Geographies geography={world}>{({ geographies }) => geographies.map((geography) => { const rawCode = String(geography.id); const isChinaRegion = rawCode === "158" || rawCode === "344" || rawCode === "446"; const code = isChinaRegion ? "156" : rawCode; const choice: Choice = { scope: "country", code, zh: isChinaRegion ? "中国" : (countryNames[code] || String(geography.properties.name || code)), en: isChinaRegion ? "China" : String(geography.properties.name || code) }; const active = selected.has(keyOf(choice)); return <Geography key={geography.rsmKey} geography={geography} tabIndex={compact ? -1 : 0} aria-label={`${choice.zh} / ${choice.en}`} onClick={() => onToggle?.(choice)} fill={active ? "#FFF3C4" : "#D9DEE3"} stroke={active ? "#E8D48A" : "#B8C0C8"} strokeWidth={compact ? .5 : .8} style={{ default: { outline: "none" }, hover: compact ? {} : { fill: active ? "#FFF3C4" : "#C7E8F7", outline: "none", cursor: "pointer" }, pressed: { outline: "none" } }}><title>{choice.zh} / {choice.en}</title></Geography>; })}</Geographies></ZoomableGroup></ComposableMap></div>; }
function MapCanvas({ scope, selected, onToggle, compact = false }: { scope: "country" | "china-province"; selected: Map<string, Choice>; onToggle?: (choice: Choice) => void; compact?: boolean }) { return scope === "china-province" ? <ChinaMap selected={selected} onToggle={onToggle} compact={compact} /> : <WorldMap selected={selected} onToggle={onToggle} compact={compact} />; }

function FootprintDialog({ initialItems, open, onClose, onSaved }: { initialItems: FootprintItem[]; open: boolean; onClose: () => void; onSaved: (items: FootprintItem[]) => void }) {
  const initial = useMemo(() => new Map(initialItems.filter((item) => item.visited).map(fromItem).filter((item): item is Choice => Boolean(item)).map((item) => [keyOf(item), item])), [initialItems]); const [selected, setSelected] = useState(initial); const [scope, setScope] = useState<"country" | "china-province">("country"); const [query, setQuery] = useState(""); const [message, setMessage] = useState(""); const [saving, setSaving] = useState(false);
  useEffect(() => { if (open) { setSelected(initial); setQuery(""); setMessage(""); } }, [open, initial]); if (!open) return null;
  const toggle = (choice: Choice) => setSelected((current) => { const next = new Map(current); const key = keyOf(choice); next.has(key) ? next.delete(key) : next.set(key, choice); return next; }); const recognize = () => { const choice = resolveChoice(query); if (!choice) { setMessage("没有识别到这个地区，请试试国家名、省份名或英文名。"); return; } setScope(choice.scope); setSelected((current) => new Map(current).set(keyOf(choice), choice)); setMessage(`已标记：${choice.zh} / ${choice.en}`); };
  const save = async () => { setSaving(true); try { const additions = [...selected.entries()].filter(([key]) => !initial.has(key)).map(([, choice]) => choice); const deletions = initialItems.filter((item) => { const choice = fromItem(item); return choice && !selected.has(keyOf(choice)); }); const created = await Promise.all(additions.map(async (choice) => { const response = await fetch("/api/footprints", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ scope: choice.scope, nameZh: choice.zh, nameEn: choice.en, code: choice.code }) }); if (!response.ok) throw new Error(); return response.json() as Promise<FootprintItem>; })); await Promise.all(deletions.map((item) => fetch(`/api/footprints/${item.id}`, { method: "DELETE" }))); onSaved([...initialItems.filter((item) => !deletions.some((deleted) => deleted.id === item.id)), ...created]); onClose(); } catch { setMessage("保存失败，请稍后再试。"); } finally { setSaving(false); } };
  return <div className="dialog-backdrop footprint-backdrop" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose(); }}><section className="footprint-dialog" role="dialog" aria-modal="true"><header><div><p>FOOTPRINTS</p><h2>选择足迹</h2></div><button type="button" className="icon-button" onClick={onClose} aria-label="关闭"><X /></button></header><div className="footprint-dialog-body"><div className="footprint-workspace"><div className="map-tabs"><button type="button" className={scope === "country" ? "active" : ""} onClick={() => setScope("country")}>全球地图</button><button type="button" className={scope === "china-province" ? "active" : ""} onClick={() => setScope("china-province")}>中国地图</button></div><div className="place-search"><input value={query} onChange={(event) => setQuery(event.target.value)} onKeyDown={(event) => { if (event.key === "Enter") recognize(); }} placeholder="输入日本、上海、Tokyo 或 California" /><button type="button" onClick={recognize}><Search size={16} />识别</button></div>{message && <p className={`recognition-message ${message.startsWith("没有") || message.startsWith("保存") ? "error" : ""}`}>{message}</p>}<MapCanvas scope={scope} selected={selected} onToggle={toggle} /><p className="map-help">滚轮或双指捏合可缩放，拖拽可平移。中国地图仅供查看，请使用上方搜索添加省份。</p></div><aside className="selected-places"><div><h3>已去过</h3><span>{selected.size} 处</span></div>{selected.size ? <ul>{[...selected.values()].map((choice) => <li key={keyOf(choice)}><span><b>{choice.zh}</b><small>{choice.en}</small></span><button type="button" onClick={() => toggle(choice)} aria-label={`删除 ${choice.zh}`}><Trash2 size={15} /></button></li>)}</ul> : <p>还没有选择地区。</p>}</aside></div><footer><button type="button" className="ghost-button" onClick={onClose}>取消</button><button type="button" className="primary-button" onClick={save} disabled={saving}>保存</button></footer></section></div>;
}

export function FootprintsPicker({ initialItems, preview = false }: { initialItems: FootprintItem[]; preview?: boolean }) { const [open, setOpen] = useState(false); const [items, setItems] = useState(initialItems); const selected = useMemo(() => new Map(items.filter((item) => item.visited).map(fromItem).filter((item): item is Choice => Boolean(item)).map((item) => [keyOf(item), item])), [items]); if (preview) return <><div className="map-thumbnails"><button type="button" className="map-thumbnail" onClick={() => setOpen(true)}><span>全球地图</span><MapCanvas scope="country" selected={selected} compact /></button><button type="button" className="map-thumbnail" onClick={() => setOpen(true)}><span>中国地图</span><MapCanvas scope="china-province" selected={selected} compact /></button></div><FootprintDialog initialItems={items} open={open} onClose={() => setOpen(false)} onSaved={setItems} /></>; return <><section className="footprint-manager-card"><div><p className="eyebrow">FOOTPRINTS</p><h2>我的足迹</h2><p>在地图上选择去过的国家和中国省份。</p></div><button type="button" className="primary-button" onClick={() => setOpen(true)}><Plus size={17} />选择足迹</button></section><section className="footprint-records"><div className="section-heading"><h2>已添加的足迹</h2><span>{items.filter((item) => item.visited).length} 处</span></div>{items.filter((item) => item.visited).length ? <div className="footprint-record-groups"><div><h3>世界足迹</h3>{items.filter((item) => item.visited && item.scope === "country").map((item) => <p key={item.id}>{item.countryNameZh || item.countryNameEn}</p>)}</div><div><h3>中国足迹</h3>{items.filter((item) => item.visited && item.scope === "china-province").map((item) => <p key={item.id}>{item.provinceNameZh || item.provinceNameEn}</p>)}</div></div> : <p className="empty-state">还没有添加足迹。</p>}</section><FootprintDialog initialItems={items} open={open} onClose={() => setOpen(false)} onSaved={setItems} /></>; }
