"use client";
import { useEffect, useMemo, useRef, useState } from "react";
import { Search, LoaderCircle } from "lucide-react";
import { usePathname, useRouter } from "next/navigation";

const names: Record<string, string> = { achievements: "成就", todos: "待办", footprints: "足迹", inspirations: "审美灵感" };
function Highlight({ value, q }: { value?: string; q: string }) { if (!value) return null; const safe = q.replace(/[.*+?^${}()|[\]\\]/g, "\\$&"); return <>{value.split(new RegExp(`(${safe})`, "ig")).map((part, i) => part.toLowerCase() === q.toLowerCase() ? <mark key={i}>{part}</mark> : part)}</>; }
export function GlobalSearch() {
  const router = useRouter(); const pathname = usePathname(); const input = useRef<HTMLInputElement>(null); const [open, setOpen] = useState(false), [q, setQ] = useState(""), [data, setData] = useState<Record<string, any[]>>({}), [loading, setLoading] = useState(false), [error, setError] = useState(""), [selected, setSelected] = useState(0);
  useEffect(() => { const onKey = (e: KeyboardEvent) => { if ((e.ctrlKey || e.metaKey) && e.key.toLowerCase() === "k") { e.preventDefault(); setOpen(true); } if (e.key === "Escape") setOpen(false); }; window.addEventListener("keydown", onKey); return () => window.removeEventListener("keydown", onKey); }, []);
  useEffect(() => { if (!open) return; const onPointerDown = (e: PointerEvent) => { const target = e.target as HTMLElement; if (!target.closest(".global-search-modal")) { setOpen(false); setQ(""); setData({}); } }; document.addEventListener("pointerdown", onPointerDown); return () => document.removeEventListener("pointerdown", onPointerDown); }, [open]);
  useEffect(() => { if (open) setTimeout(() => input.current?.focus(), 0); }, [open]);
  useEffect(() => { if (!q.trim()) { setData({}); return; } const timer = setTimeout(async () => { setLoading(true); setError(""); try { const r = await fetch(`/api/search?q=${encodeURIComponent(q)}`); if (!r.ok) throw new Error(); setData(await r.json()); setSelected(0); } catch { setError("搜索失败，请稍后重试。"); } finally { setLoading(false); } }, 300); return () => clearTimeout(timer); }, [q]);
  const groups = useMemo(() => Object.keys(names).map((key) => ({ key, items: data[key] || [] })).filter((x) => x.items.length), [data]); const flat = groups.flatMap((x) => x.items);
  useEffect(() => { const target = sessionStorage.getItem("global-search-target"); if (!target) return; const timer = setTimeout(() => { const nodes = [...document.querySelectorAll("h1,h2,h3,strong")]; const match = nodes.find((node) => node.textContent?.trim() === target); const card = match?.closest("article,section,.inspiration-row,.todo-item"); if (card) { card.scrollIntoView({ behavior: "smooth", block: "center" }); card.classList.add("global-search-focus"); setTimeout(() => card.classList.remove("global-search-focus"), 1800); sessionStorage.removeItem("global-search-target"); } }, 450); return () => clearTimeout(timer); }, [pathname]);
  const close = () => { setOpen(false); setQ(""); setData({}); }; const go = (item: any) => { sessionStorage.setItem("global-search-target", item.title); close(); router.push(item.url); };
  const keyboard = async (e: React.KeyboardEvent) => { if (e.key === "ArrowDown") { e.preventDefault(); setSelected((x) => Math.min(x + 1, Math.max(flat.length - 1, 0))); } else if (e.key === "ArrowUp") { e.preventDefault(); setSelected((x) => Math.max(x - 1, 0)); } else if (e.key === "Enter") { e.preventDefault(); if (flat[selected]) { go(flat[selected]); return; } if (!q.trim()) return; setLoading(true); try { const response = await fetch(`/api/search?q=${encodeURIComponent(q.trim())}`); if (!response.ok) throw new Error(); const result = await response.json() as Record<string, any[]>; const first = ["achievements", "todos", "footprints", "inspirations"].flatMap((key) => result[key] || [])[0]; if (first) go(first); else setData(result); } catch { setError("搜索失败，请稍后重试。"); } finally { setLoading(false); } } };
  return <><div className="global-search-entry"><Search size={17}/><input value={q} onChange={(e) => { setQ(e.target.value); setOpen(true); }} onFocus={() => setOpen(true)} onKeyDown={keyboard} placeholder="搜索成就、待办、足迹、灵感..." aria-label="全局搜索"/><kbd>Ctrl K</kbd></div><button className="global-search-mobile" onClick={() => setOpen(true)} aria-label="打开全局搜索"><Search size={19}/></button>{open && <div className="global-search-overlay" onMouseDown={(e) => e.target === e.currentTarget && close()}><div className="global-search-modal" role="dialog" aria-modal="true"><div className="global-search-modal-input"><Search size={19}/><input ref={input} autoFocus value={q} onChange={(e) => setQ(e.target.value)} onKeyDown={keyboard} placeholder="搜索成就、待办、足迹、灵感..." aria-label="搜索站内内容"/><kbd>Esc</kbd></div>{loading && <p className="global-search-status"><LoaderCircle className="spin" size={18}/>正在搜索...</p>}{error && <p className="global-search-status error">{error}</p>}{!loading && !error && q && !flat.length && <p className="global-search-status">没有找到相关内容，试试其他关键词。</p>}<div className="global-search-results">{groups.map((group) => <section key={group.key}><header><h2>{names[group.key]}</h2>{group.items.length >= 5 && <a href={`/${group.key === "inspirations" ? "inspiration" : group.key}?q=${encodeURIComponent(q)}`}>查看全部</a>}</header>{group.items.map((item, i) => <button key={`${group.key}-${item.id}`} className={`global-search-result ${flat.indexOf(item) === selected ? "selected" : ""}`} onClick={() => go(item)}><strong><Highlight value={item.title} q={q}/></strong><span className="badge">{item.status || item.type || item.category || (item.visited ? "已去过" : "未去过")}</span><p><Highlight value={item.snippet || item.subtitle} q={q}/></p></button>)}</section>)}</div></div></div>}</>;
}
