"use client";
import { useEffect } from "react";

type ToolDefinition = { name:string;title:string;description:string;inputSchema:object;annotations:{readOnlyHint:boolean;untrustedContentHint:boolean};execute:(input:unknown)=>Promise<unknown> };
declare global { interface Document { modelContext?: { registerTool:(tool:ToolDefinition,options?:{signal?:AbortSignal})=>void|Promise<void> } } }

async function post(path:string,input:unknown){const response=await fetch(path,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(input)});if(!response.ok){const data=await response.json() as {error?:string};throw new Error(data.error||"保存失败")}window.location.reload();return{saved:true}}
export function WebMcpTools(){useEffect(()=>{const context=document.modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();const tools:ToolDefinition[]=[
{name:"create_todo",title:"新增待办",description:"在拾光簿中新增一条待办。",inputSchema:{type:"object",properties:{title:{type:"string"},description:{type:"string"},dueDate:{type:"string"},priority:{enum:["low","medium","high"]},status:{enum:["todo","doing","done"]},tags:{type:"array",items:{type:"string"}},isPublic:{type:"boolean"}},required:["title","priority","status"],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:(input)=>post("/api/todos",{description:"",dueDate:"",tags:[],isPublic:false,...input as object})},
{name:"create_achievement",title:"新增成就",description:"在拾光簿中新增一条成就记录。",inputSchema:{type:"object",properties:{title:{type:"string"},type:{enum:["项目","比赛","实习","活动","证书","其他"]},startDate:{type:"string"},description:{type:"string"},tags:{type:"array",items:{type:"string"}}},required:["title","type","startDate"],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:(input)=>post("/api/achievements",{role:"",organization:"",description:"",tags:[],isPublic:false,isPinned:false,...input as object})},
{name:"create_footprint",title:"新增足迹",description:"在拾光簿中新增一处国家或中国省份足迹。",inputSchema:{type:"object",properties:{scope:{enum:["country","china-province"]},nameZh:{type:"string"},nameEn:{type:"string"},code:{type:"string"},visitedAt:{type:"string"},note:{type:"string"}},required:["scope","nameZh","code"],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:(input)=>post("/api/footprints",{nameEn:"",visitedAt:"",note:"",...input as object})},
];for(const tool of tools)void Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});return()=>lifecycle.abort()},[]);return null}
